apiVersion: v1
kind: Service
metadata:
  name: "${parameters.application}"
spec:
  ports:
    - port: "${parameters.port}"
      protocol: TCP
  selector:
    io.chassi.application: "${parameters.application}"