name: Demo Release
on:
  push:
    tags:
    - "v[0-9]+.[0-9]+.[0-9]+"

env:
  CONTAINER_REGISTRY: chassidemo

concurrency:
  group: pr-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  envsetup:
    name: set some basic output information for triggered workflows
    runs-on: self-hosted
    outputs:
      chassi-version: ${{ steps.set-chassi-version.outputs.chassi-version }}
    steps:
      - name: "emit chassi version"
        id: set-chassi-version
        run: |
          echo ::set-output name=chassi-version::${GITHUB_REF##*/v}
  publish-pokemons:
    needs: [envsetup]
    runs-on: jammy
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Login to Docker Registry
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DEMO_DOCKER_USERNAME }}
          password: ${{ secrets.DEMO_DOCKER_PASSWORD }}
      - name: Setup QEMU
        uses: docker/setup-qemu-action@v2
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build Ubuntu Image
        uses: docker/build-push-action@v3
        with:
          context: examples/pokemon/
          file: pokemon.Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            "${{ env.CONTAINER_REGISTRY }}/pokemon:${{ needs.envsetup.outputs.chassi-version }}"
            "${{ env.CONTAINER_REGISTRY }}/pokemon:latest"
